spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:9090/auth/realms/myrealm
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
      schema.registry.url: http://schema-registry:8090
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://customer-db:5432/customerdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
server:
  port: 8383
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
app:
  kafka:
    customer:
      topic: customer-events
keycloak:
  realm: myrealm
  auth-server-url: http://localhost:9090/auth
  resource: customer-service
  credentials:
    secret: I8MfLnNLtSrlMjWiZEhJekGx2zzZvt24
  bearer-only: true
camunda:
  client:
    mode: simple
    zeebe:
      gateway-address: 127.0.0.1:26500
      security:
        plaintext: true
kie:
  server:
    url: http://kie-server:8080/kie-server/services/rest/server
    user: kieserver
    pwd: kieserver1!
    container-id: customer_service_1.0.0-SNAPSHOT
    session-name: defaultKieSession